### ISSUE TITLE
Service name  and EPG on 88E SAT can not correctly decode,can openpli team merge nx111 some changes into 6.2 or rc branch

### ISSUE THREAD

**Issue by opfans** [OpenPLi/enigma2#1898]
I am using octagon  sf4008 receiver. The service  name and EPG on 88E SAT can not correctly decode .the first char of string is 0x15,but it is encoded by utf16be.Merge nx111 changes and add config in encoding.conf, it can show string correctly.It tested OK on openatv.Can openpli team merge nx111 estring: [fixed] support enforced table from encoding config file on develop branch into release 6.2 or rc branch.BIG THANKS to openpli team!

**Comment by WanWizard** [comment]
What do you mean by "nx111 changes"? Link?

**Comment by opfans** [comment]
> What do you mean by "nx111 changes"? Link?

the link here https://github.com/OpenPLi/enigma2/commit/fdc19981c17a1895896a98ca3df15d82745e6efe

**Comment by opfans** [comment]
it works OK on openatv and openhdf

**Comment by WanWizard** [comment]
It was reverted in RC two days later, @littlesat can you remember why?

edit: correction, it was reverted and a day later committed again by you.

**Comment by opfans** [comment]
my hd51 box can use openpli image ,hope you can fix this issue,BIG THANKS to openpli team.

**Comment by pr2git** [comment]
Is this problem solved for you in OpenPLi 7.0?

**Comment by littlesat** [comment]
It was reverted due to side effects on other providers reported by other users... but as far I remember other changes should solve it... that should be in 7.0...

**Comment by opfans** [comment]
Service name and EPG on 88E SAT  still cant display correctly with OpenPLi 7.0.this commit https://github.com/openhdf/enigma2/commit/a2510cd52fac16180e37552816e031eb06c7781a#diff-bb25b7b5f2105e95732e75b7477458d5  works on openatv, openhdf openvix .you can merge from https://github.com/openhdf/enigma2/commit/a2510cd52fac16180e37552816e031eb06c7781a#diff-bb25b7b5f2105e95732e75b7477458d5
It works well ,there is no conflict with other providers.

**Comment by littlesat** [comment]
As far Incan see also on oe-a images it was reverted... but it seems they played around with another patch which really looks somehow ‘ugly’ ... they solve the issue and also did a lot of style changes in one patch which is not done...  you sure it also fits in our code? Can you offer a patch for us as we cannot test it non of us has 88 East!
This patch cannot be merged beside style
It also includes a verbose change in the debug log... the Q of the patch is terrible

**Comment by littlesat** [comment]
As far I can see this is included in openpli so it should work!!!https://github.com/OpenPLi/enigma2/commit/3902b5a71f7ca4aa0d77ae97bdc8e7f4dbb2beb3
https://github.com/OpenPLi/enigma2/commit/fdc19981c17a1895896a98ca3df15d82745e6efe
At least the decoding is there... but it might miss some code in the scanning
Stuff...
Might be nx111 did forget something?

**Comment by nx111** [comment]
The changes about scanning be included in openpli always.

**Comment by opfans** [comment]
please close this issue ,thanks openpli team
