### ISSUE TITLE
OpenSubtitles - Subtitles support

### ISSUE THREAD

**Issue by opensubtitles** [OpenPLi/enigma2#3904]
Hi guys,

we are receiving quite a lot of request, how to make opensubtitles work again in Enigma. we announcement EOL of old API, please read this:

https://forum.opensubtitles.org/viewtopic.php?t=17930#p47873

Either allow users to use opensubtitles.org username and password, or better, implement API of opensubtitles.com

Thank you

**Comment by WanWizard** [comment]
Thanks for the headsup. But afaik, we don't use opensubtitles anywhere. Perhaps a third-party plugin?

**Comment by opensubtitles** [comment]
I am not sure, we just receive questions how to enable subtitles again. If you can find out which plugin is using our services, it would be great, so I can contact them directly, but I guess it is not maintained anymore...

**Comment by WanWizard** [comment]
I've posted a notice on our forum: https://forums.openpli.org/topic/97560-opensubtitles/

There is a lot of junk out there that is not maintained anymore, but as most of these plugin builders don't make their source public so we can build from it, but create binaries they float on different forums, it is difficult to do anything once they're out.

**Comment by jbleyel** [comment]
Hello @opensubtitles , we are planning to use this new repro. I have started this but it‘s not finished:  

https://github.com/oe-alliance/subssupport

**Comment by popking159** [comment]
> Hello @opensubtitles , we are planning to use this new repro. I have started this but it‘s not finished:
> 
> https://github.com/oe-alliance/subssupport

I want to help get this plugin back to life , I made some modifications to subtitles providers , you can try it and add it to the feed , of course it is not finished but it works and will help download and play external subtitles.

https://www.mediafire.com/file/v9c4y4k7fl9rybb/enigma2-plugin-extensions-subssupport_1.7.0-r10-py3_all.ipk/file

**Comment by jbleyel** [comment]
Can you please make a pull request here ->

https://github.com/oe-alliance/subssupport

**Comment by opensubtitles** [comment]
@popking159 good job. Did you implement new API, or it is using old one with username and password ?

**Comment by jbleyel** [comment]
Hello @popking159 , your changes are probably working but your code needs a cleanup.
I have compared your code with my last version and you have a lot of issues what I have already fixed.

**Comment by popking159** [comment]
> Hello @popking159 , your changes are probably working but your code needs a cleanup. I have compared your code with my last version and you have a lot of issues what I have already fixed.

Yes I know , as I said , it is not finished but it works .
Thanks for help

**Comment by popking159** [comment]
> @popking159 good job. Did you implement new API, or it is using old one with username and password ?

Scraping only , no need for API or username

**Comment by littlesat** [comment]
Scraping is not the way you should do it.
API is the way
A small change on the website stop scraping or needs another change more frequently.

**Comment by opensubtitlesdev** [comment]
> > @popking159 good job. Did you implement new API, or it is using old one with username and password ?
> 
> Scraping only , no need for API or username

I'm the main developer of the opensubtitles.com site and API, I jump in....

Sorry that's really not a viable option, you can't authenticate, you'll be limited to 10 subtitles per day, and have to deal with the download delay. plus all the routing for the search will be changed soon, so it will definitely not work for long.

the API is free, it's documented, it gives you full access to the content, an so much more.....

so I'm sorry but this need an entire rewrite using the API https://opensubtitles.stoplight.io/docs/opensubtitles-api/ we're around and happy to help if you have questions

**Comment by popking159** [comment]
> > > [@popking159](https://github.com/popking159) good job. Did you implement new API, or it is using old one with username and password ?
> > 
> > 
> > Scraping only , no need for API or username
> 
> I'm the main developer of the opensubtitles.com site and API, I jump in....
> 
> Sorry that's really not a viable option, you can't authenticate, you'll be limited to 10 subtitles per day, and have to deal with the download delay. plus all the routing for the search will be changed soon, so it will definitely not work for long.
> 
> the API is free, it's documented, it gives you full access to the content, an so much more.....
> 
> so I'm sorry but this need an entire rewrite using the API https://opensubtitles.stoplight.io/docs/opensubtitles-api/ we're around and happy to help if you have questions

You can try this 
`https://www.mediafire.com/file/2ball75hlovpqsi`
I implemented API partially in authentication and downloading subtitles, and scraping for searching, I will try to use API for searching.

**Comment by opensubtitles** [comment]
FYI we can not test your stuff, not enigma2 users here...

**Comment by jbleyel** [comment]
Hello @popking159 , nice work but please continue here -> https://github.com/oe-alliance/subssupport
I have taken your changes but I have also made a full cleanup.
Some of the seeker are still not working or have a lot of debug code.

**Comment by opensubtitlesdev** [comment]
I still see the "list_subtitles" calling on the www.opensubtitles.com public site.

please totally rewrite that part, any plugin MUST EXCLUSIVELY USE the API

do not publish, this plugin will break the moment our upgraded search will be released (currently in test)

**Comment by jbleyel** [comment]
Can we please close this issue here because it’s not an enigma issue.
The git is here -> https://github.com/oe-alliance/subssupport
